name: GetNit
options:
  bundleIdPrefix: com.jotoltd
  deploymentTarget:
    iOS: 17.0
targets:
  GetNit:
    type: application
    platform: iOS
    sources:
      - GetNit/Sources
    info:
      path: GetNit/Info.plist
      properties:
        CFBundleDisplayName: GetNit
        NSPhotoLibraryUsageDescription: GetNit needs access to your photo library so you can swipe through and keep or delete photos.
        UILaunchStoryboardName: LaunchScreen
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.digitalgaff.getnit
        CURRENT_PROJECT_VERSION: 1
        MARKETING_VERSION: 1.0
        DEVELOPMENT_TEAM: 3B9B42HAF9
        CODE_SIGN_STYLE: Automatic
        CODE_SIGN_IDENTITY: "Apple Development"
        TARGETED_DEVICE_FAMILY: "1"
